version: "3.0"
services:
  db:
    container_name: ""
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=
      - POSTGRES_PASSWORD=
      - POSTGRES_DB=
    ports:
      - "7546:5432"
    networks:
      - custom
networks:
  custom:
    driver: bridge