version: "3.0"
services:
  db:
    container_name: "Motivation"
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=Provonsal
      - POSTGRES_PASSWORD=vkijlonmssf
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    networks:
      - custom
networks:
  custom:
    driver: bridge